#ifndef OXYGENDRAGON_SOLDER_DETECTION_MAIN_FUNCTIONS_H_
#define OXYGENDRAGON_SOLDER_DETECTION_MAIN_FUNCTIONS_H_

void setup();

void loop();

#endif  // TENSORFLOW_LITE_MICRO_EXAMPLES_HANDWRITING_MAIN_FUNCTIONS_H_
