#ifndef OXYGENDRAGON_SOLDER_DETECTION_MAIN_FUNCTIONS_H_
#define OXYGENDRAGON_SOLDER_DETECTION_MAIN_FUNCTIONS_H_

void setup();

void loop();

#endif  // OXYGENDRAGON_SOLDER_DETECTION_MAIN_FUNCTIONS_H_
